export const groups = [
  {
    name: "Mindfulness",
    color: "mediumpurple",
    id: 0,
    status: true,
    sub_groups: [
      "Meditation",
      "Acceptance",
      "Positivity",
      "Serving",
      "Awareness",
    ],
    goal: "Achieve clarity of mind",
    main_question: "Do I know what to do now, what is next?",
    check_points: [
      "I am calm and focused most of the day",
      "I stay focused in good and bad times",
      "I see others and feel connected with them",
    ],
  },
  {
    name: "Leadership",
    color: "darkcyan",
    id: 1,
    status: true,
    sub_groups: [
      "Inclusion",
      "Appreciaton",
      "Listening",
      "Questioning",
      "Coaching",
    ],
    goal: "Build a habit for leadership",
    main_question: "Do I see the opportinities and defend against threats?",
    check_points: [
      "There is the clear definition, the structure and plan for the project",
      "Priorities and task queue is working",
      "Resources are available and growing",
    ],
  },
  {
    name: "Productivity",
    color: "darkorange",
    id: 2,
    status: true,
    sub_groups: ["Planning", "Review", "Journal", "Composing"],
    goal: "Increase the amount of meaningful work per day",
    main_question: "How do I use my resources more efficiently?",
    check_points: [
      "There is a plan for today and some plan for this week",
      "Plan is done at least for 50%",
      "Any changes in plan cause better definition for something",
    ],
  },
  {
    name: "Health",
    color: "mediumseagreen",
    id: 3,
    status: true,
    sub_groups: [
      "Exersizing",
      "Healthy eating",
      "Good posture",
      "Deep breathing",
    ],
    goal: "Pay attention to health",
    main_question: "What did I add to my health today?",
    check_points: [
      "I feel healthy",
      "I notice when I need to switch task, get rest, pause and watch",
      "I often notice my breathing",
    ],
  },
  {
    name: "Self Upgrade",
    color: "tomato",
    id: 4,
  },
  {
    name: "JavaScript",
    color: "darkgreen",
    id: 5,
  },
  {
    name: "Software Architecture",
    color: "slateblue",
    id: 4,
  },
  {
    name: "Software Architecture",
    color: "royalblue",
    id: 4,
  },
];
