# DEV Environment
# Deployment patch file template to update container image with new build accordingly
spec:
    template:
      spec:
        containers:
        - image: docker.apple.com/vvs-uat/cvp-data-collector:b_${BUILD_NUMBER}
          name: cvp-data-collector