export const userActionTypes = {
  LOGIN_WITH_EMAIL_START: "LOGIN_WITH_EMAIL_START",
  LOGIN_WITH_EMAIL_SUCCESS: "LOGIN_WITH_EMAIL_SUCCESS",
  LOGIN_WITH_EMAIL_FAILURE: "LOGIN_WITH_EMAIL_FAILURE",

  SIGNIN_WITH_GOOGLE_START: "SIGNIN_WITH_GOOGLE_START",
  SIGNIN_WITH_GOOGLE_SUCCESS: "SIGNIN_WITH_GOOGLE_SUCCESS",
  SIGNIN_WITH_GOOGLE_FAILURE: "SIGNIN_WITH_GOOGLE_FAILURE",

  SIGN_UP_WITH_EMAIL_START: "SIGN_UP_WITH_EMAIL_START",
  SIGN_UP_WITH_EMAIL_SUCCESS: "SIGN_UP_WITH_EMAIL_SUCCESS",
  SIGN_UP_WITH_EMAIL_FILURE: "SIGN_UP_WITH_EMAIL_FILURE",

  SIGNUP_WITH_GOOGLE_ASYNC: "SIGNUP_WITH_GOOGLE_ASYNC",
  SIGNUP_WITH_GOOGLE_START: "SIGNUP_WITH_GOOGLE_START",
  SIGNUP_WITH_GOOGLE_SUCCESS: "SIGNUP_WITH_GOOGLE_SUCCESS",
  SIGNUP_WITH_GOOGLE_FAILURE: "SIGNUP_WITH_GOOGLE_FAILURE",

  SET_USER: "SET_USER",
};

export const set_user = (user) => ({
  type: userActionTypes.SET_USER,
  payload: user,
});
